modLoader="javafml"
loaderVersion="*"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Healing%20Soup"
logoFile="icon.png"

[[mods]]
modId="healingsoup"
version="5.5"
displayName="Healing Soup"
displayURL="https://serilum.com/mod/healing-soup"
authors="Serilum"
description='''Soup heals hearts. Adds cactus soup, mushroom soup and chocolate milk items and recipes.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, AnyankaT, aternosorg, Cherriesaurus, Linda Jansen, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate Appreciate it! <3   
'''

[[dependencies.healingsoup]]
    modId="collective"
    mandatory=true
    versionRange="[8.40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.healingsoup]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.3]"
    ordering="NONE"
    side="BOTH"
