modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Healing%20Soup"
logoFile="icon.png"

[[mods]]
modId="healingsoup"
version="5.1"
displayName="Healing Soup"
displayURL="https://serilum.com/mod/healing-soup"
authors="Rick South"
description='''Soup heals hearts. Adds cactus soup, mushroom soup and chocolate milk items and recipes.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, kate1073, Michael W. S., Tyler Behl, XAgent   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.healingsoup]]
    modId="collective"
    type="required"
    versionRange="[7.89,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.healingsoup]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.2,1.21.3]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "healingsoup.mixins.json"